version: '2'
services:
  solr:
    build: .
    volumes:
      - .:/lucene-solr
    ports:
      - "8983:8983"
    network_mode: host
    command:
      '/opt/solr-5.3.2-SNAPSHOT/bin/solr start -f -Dsolr.solr.home=/solr-home -p 8983'
