version: '2'
services:
  solr:
    build: .
    volumes:
      - .:/lucene-solr
    ports:
      - "8984:8984"
    command:
      '/opt/solr-5.3.2-SNAPSHOT/bin/solr start -f -Dsolr.solr.home=/solr-home -p 8984'
